# Generated by Django 6.0.2 on 2026-03-10 00:28

import app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Defendant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('id_no', models.CharField(max_length=20, unique=True)),
                ('license_no', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('alt_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('physical_address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=True)),
                ('preferred_method', models.CharField(choices=[('all', 'All'), ('email', 'Email'), ('sms', 'SMS')], default='all', max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defendant_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Judiciary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(max_length=20, unique=True)),
                ('rank', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Nampol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.officer')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_issued', models.CharField(default=app.models.generate_ticket_number, max_length=100, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('plate_no', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehicle_make', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_model', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_color', models.CharField(blank=True, max_length=30, null=True)),
                ('vehicle_year', models.CharField(blank=True, max_length=4, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('gps_coordinates', models.CharField(blank=True, max_length=50, null=True)),
                ('road_number', models.CharField(blank=True, max_length=20, null=True)),
                ('road_type', models.CharField(blank=True, choices=[('national', 'National Road (B1, B2, B3, etc.)'), ('district', 'District Road (M1, M2, etc.)'), ('urban', 'Urban Road'), ('street', 'Street'), ('avenue', 'Avenue'), ('other', 'Other')], max_length=20, null=True)),
                ('region', models.CharField(blank=True, choices=[('khomas', 'Khomas Region'), ('erongo', 'Erongo Region'), ('omasati', 'Omasati Region'), ('oshana', 'Oshana Region'), ('oshikoto', 'Oshikoto Region'), ('ohangwena', 'Ohangwena Region'), ('kunene', 'Kunene Region'), ('kavango_east', 'Kavango East Region'), ('kavango_west', 'Kavango West Region'), ('zambezi', 'Zambezi Region'), ('hardap', 'Hardap Region'), ('karas', 'Karas Region')], max_length=50, null=True)),
                ('violation_type', models.CharField(choices=[('speeding', 'Speeding'), ('red_light', 'Red Light Violation'), ('illegal_parking', 'Illegal Parking'), ('dui', 'Driving Under Influence (DUI)'), ('no_license', 'Driving Without License'), ('expired_license', 'Expired License'), ('no_registration', 'No/Expired Vehicle Registration'), ('no_inspection', 'Failed Vehicle Inspection'), ('cell_phone', 'Using Cell Phone While Driving'), ('seatbelt', 'Not Wearing Seatbelt'), ('reckless', 'Reckless Driving'), ('overloading', 'Vehicle Overloading'), ('one_way', 'One-Way Street Violation'), ('stop_sign', 'Failure to Stop at Stop Sign'), ('no_helmet', 'Motorcycle - No Helmet'), ('illegal_turn', 'Illegal Turn/U-Turn'), ('pedestrian', 'Pedestrian Crossing Violation'), ('drug_driving', 'Driving Under Drugs'), ('hit_run', 'Hit and Run'), ('unroadworthy', 'Unroadworthy Vehicle'), ('wrong_lane', 'Wrong Lane Usage'), ('tailgating', 'Tailgating'), ('overtaking', 'Illegal Overtaking'), ('no_insurance', 'No Motor Vehicle Insurance'), ('unlicensed_vehicle', 'Unlicensed Vehicle'), ('noise_violation', 'Excessive Noise'), ('other', 'Other Offence')], default='speeding', max_length=50)),
                ('violation_time', models.TimeField(blank=True, null=True)),
                ('officer_notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('disputed', 'Disputed'), ('court', 'Court'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_tickets', to='app.officer')),
            ],
        ),
        migrations.CreateModel(
            name='OfficerManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('badge', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('action', models.CharField(blank=True, max_length=50, null=True)),
                ('active', models.BooleanField(default=True)),
                ('officer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='management', to='app.officer')),
                ('assigned_tickets', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='DefendantFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='defendant_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('defendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.defendant')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='CourtDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_court_dates', to=settings.AUTH_USER_MODEL)),
                ('judge', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.judiciary')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='court_date', to='app.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ticket_issued', 'Ticket Issued'), ('ticket_paid', 'Ticket Paid'), ('court_date_set', 'Court Date Set'), ('message_sent', 'Message Sent'), ('attachment_added', 'Attachment Added'), ('user_login', 'User Login'), ('user_logout', 'User Logout')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ticket_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_type', models.CharField(choices=[('photo', 'Photo'), ('document', 'Document'), ('video', 'Video'), ('evidence', 'Evidence'), ('other', 'Other')], default='document', max_length=50)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='app.ticket')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to='app.officer')),
            ],
        ),
        migrations.CreateModel(
            name='TicketManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('officer', 'Officer'), ('judiciary', 'Judiciary'), ('ministry', 'Ministry'), ('admin', 'Admin'), ('natisadmin', 'NaTIS Admin'), ('nampoladmin', 'Nampol Admin')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Roles',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_no', models.CharField(help_text='Vehicle registration plate number', max_length=20, unique=True)),
                ('vin', models.CharField(help_text='Vehicle Identification Number (VIN)', max_length=50, unique=True)),
                ('engine_no', models.CharField(blank=True, help_text='Engine number', max_length=50, null=True)),
                ('vehicle_make', models.CharField(help_text='Vehicle manufacturer (e.g., Toyota, BMW)', max_length=50)),
                ('vehicle_model', models.CharField(help_text='Vehicle model name', max_length=50)),
                ('vehicle_color', models.CharField(help_text='Vehicle color', max_length=30)),
                ('vehicle_year', models.CharField(help_text='Year of manufacture', max_length=4)),
                ('vehicle_type', models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('hatchback', 'Hatchback'), ('pickup', 'Pickup'), ('truck', 'Truck'), ('bus', 'Bus'), ('motorcycle', 'Motorcycle'), ('van', 'Van'), ('minibus', 'Minibus'), ('other', 'Other')], default='sedan', max_length=50)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid'), ('other', 'Other')], default='petrol', max_length=20)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('registration_expiry', models.DateField(help_text='Vehicle registration expiry date')),
                ('roadworthy_cert_no', models.CharField(blank=True, help_text='Roadworthy certificate number', max_length=50, null=True)),
                ('roadworthy_expiry', models.DateField(blank=True, help_text='Roadworthy certificate expiry date', null=True)),
                ('insurance_company', models.CharField(blank=True, max_length=100, null=True)),
                ('insurance_policy_no', models.CharField(blank=True, max_length=50, null=True)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('scrapped', 'Scrapped'), ('stolen', 'Stolen')], default='registered', max_length=20)),
                ('seating_capacity', models.IntegerField(default=5, help_text='Number of seats')),
                ('gross_vehicle_mass', models.IntegerField(blank=True, help_text='Gross vehicle mass in kg', null=True)),
                ('tare_mass', models.IntegerField(blank=True, help_text='Tare mass in kg', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='Registered owner of the vehicle', on_delete=django.db.models.deletion.CASCADE, related_name='owned_vehicles', to='app.defendant')),
            ],
            options={
                'ordering': ['-registration_date'],
            },
        ),
    ]
