# Generated by Django 6.0.3 on 2026-03-10 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('id_no', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('description', models.TextField()),
                ('last_seen_location', models.CharField(max_length=200)),
                ('last_seen_date', models.DateTimeField()),
                ('gps_coordinates', models.CharField(blank=True, max_length=50, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='missing_persons/')),
                ('status', models.CharField(choices=[('missing', 'Missing'), ('found', 'Found'), ('deceased', 'Deceased')], default='missing', max_length=20)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_missing_persons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('general', 'General'), ('traffic', 'Traffic'), ('security', 'Security'), ('weather', 'Weather'), ('events', 'Events'), ('policy', 'Policy Update')], default='general', max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('image', models.FileField(blank=True, null=True, upload_to='news/')),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_news', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='TrafficIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('traffic_jam', 'Traffic Jam'), ('accident', 'Road Accident'), ('road_closure', 'Road Closure'), ('construction', 'Construction/Road Works'), ('weather', 'Weather Hazard'), ('police_check', 'Police Checkpoint'), ('event', 'Special Event'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=200)),
                ('gps_coordinates', models.CharField(blank=True, max_length=50, null=True)),
                ('road_number', models.CharField(blank=True, max_length=20, null=True)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WarrantOfArrest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('id_no', models.CharField(max_length=20)),
                ('alias', models.CharField(blank=True, max_length=100, null=True)),
                ('offense', models.TextField()),
                ('warrant_number', models.CharField(max_length=50, unique=True)),
                ('issue_date', models.DateField()),
                ('issued_by', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('executed', 'Executed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_warrants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
