# Generated by Django 6.0.3 on 2026-03-14 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_missingperson_news_trafficincident_warrantofarrest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('payment_plan', 'Payment Plan'), ('court', 'Escalated to Court')], default='active', max_length=20)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='case', to='app.ticket')),
            ],
        ),
    ]
