# Generated by Django 6.0.3 on 2026-03-15 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='assigned_judge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to='app.judiciary'),
        ),
        migrations.AddField(
            model_name='case',
            name='available',
            field=models.BooleanField(default=True, help_text='Available for judge assignment'),
        ),
        migrations.AddField(
            model_name='case',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='judiciary_notified',
            field=models.BooleanField(default=False, help_text='Judiciary notified of availability'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('ticket_issued', 'Ticket Issued'), ('ticket_paid', 'Ticket Paid'), ('court_date_set', 'Court Date Set'), ('message_sent', 'Message Sent'), ('case_claimed', 'Case Claimed'), ('defendant_notified', 'Defendant Notified'), ('attachment_added', 'Attachment Added'), ('user_login', 'User Login'), ('user_logout', 'User Logout')], max_length=50),
        ),
    ]
